### GET all posts
GET http://localhost:3000/posts

### POST a new post
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Cats that are cool",
    "author": "Tom"
}